insert into USERS values(1, 'admin','admin','21232f297a57a5a743894a0e4a801fc3');
insert into USERS values(2, 'login','login','5f4dcc3b5aa765d61d8327deb882cf99');

insert into ROLES values(1, 1, 'ROLE_ADMIN');
insert into ROLES values(2, 2, 'ROLE_ADMIN');

insert into TAGS values(1, 'politics');
insert into TAGS values(2, 'health');
insert into TAGS values(3, 'sport');
insert into TAGS values(4, 'art');
insert into TAGS values(5, 'science');
insert into TAGS values(6, 'people');
insert into TAGS values(7, 'style');
insert into TAGS values(8, 'world');
insert into TAGS values(9, 'business');

insert into AUTHORS values(1, 'Michael Lewis', null);
insert into AUTHORS values(2, 'Gerald Hall', null);
insert into AUTHORS values(3, 'Denise Campbell', null);
insert into AUTHORS values(4, 'Barbara Green', null);
insert into AUTHORS values(5, 'Victor Davis', null);
insert into AUTHORS values(6, 'Jessica Turner', null);
insert into AUTHORS values(7, 'Sara Cook', null);
insert into AUTHORS values(8, 'Laura Murphy', null);
insert into AUTHORS values(9, 'Anna Brown', null);
insert into AUTHORS values(10, 'Carlos	Butler', null);

insert into NEWS values(1, 'North Korea','North Korea fires ballistic missiles, US officials say','North Korea has test-fired two ballistic missiles, the latest in a series of rocket launches. US officials said the medium-range missiles, launched off the east coast, flew about 800km (500 miles) before falling into the water.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(2, 'Kon-Tiki','Attempt to recreate Kon-Tiki voyage ends with rescue','Authorities in Chile say they have rescued 14 people from two rafts, ending an attempt to emulate the famous Kon-Tiki voyage of 1947. The "Kon-Tiki2" expedition began in Peru in November and the rafts reached Chile''s Easter Island in 43 days.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(3, 'Disney princesses','If Disney princesses were Filipina','Once upon a time, Disney''s famous princesses were re-imagined as zombies and even as bowls of water. But one of the most intriguing spins on the iconic characters is what is happening among fans in the Philippines. The hashtag #IfDisneyPrincessesWerePinay regularly appears on Twitter, much to the delight of local fans.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(4, 'Lilly Singh','The rise and rise of Lilly Singh','Lilly Singh is talking about appearing on Forbes'' Highest Paid YouTube Stars of 2015 list, days before she takes her show to Mumbai. Singh, 27 and from Toronto, uses the pseudonym IISuperwomanII when speaking to her social media following of more than 12 million people. She earned an estimated $2.5m last year from her two YouTube channels, a 27-city world tour and her own movie, among other projects. Her journey as a digital creator began in 2010. At the start, much of her content focused on her Indian heritage and highlighted her ethnic background.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(5, 'Nokia','Nokia: Life after the fall of a mobile phone giant','On the face of it the small Finnish town of Nokia looks wholly unremarkable. A few squat blocks of flats are nestled in the winter snow, and along the heavily gritted main road is a small strip of shops, restaurants and a discount supermarket. There''s little sign that this quiet backwater once gave its name to the company that revolutionised the mobile phone industry in the late 1990s and helped turn Finland''s economy into one of the most prosperous in the world.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(6, 'The Tunisian women','The Tunisian women locked up for smoking a joint','It is no surprise that Tunisia''s prisons are overcrowded as it''s relatively easy to end up there. In one prison I met two women who were locked up for smoking a joint. The dreary reception hall of Menouba prison lies between the gates of freedom and captivity.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(7, 'Profile of US','Merrick Garland: Profile of US Supreme Court hopeful','Veteran appeals court judge Merrick Garland is President Barack Obama''s nominee to the US Supreme Court. If successful, he would replace conservative Justice Antonin Scalia, who died in February. Who is Merrick Garland? Judge Garland, 63, is the chief judge of the Washington appeals court and a former prosecutor. The Harvard graduate would be the oldest candidate nominated for the Supreme Court since the 1970s.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(8, 'Pakistani bill','Why is a Pakistani bill to protect women unpopular?','The United Nation''s Gender Inequality Index puts Pakistan 147th in a list of 188 countries because of its poor record on women''s health, education, political empowerment and economic status. This is mainly because Pakistan is a heavily patriarchal society with a strong feudal value system, in which women are treated as domestic property. Increased urbanisation and the concomitant fading of the joint family system have exposed women to further abuses.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(9, 'Mafia state','South Africa Gupta row: ANC''s Mantashe warns of ''mafia state''','South Africa risks turning into a "mafia state", a senior governing party official has warned, as pressure grows on President Jacob Zuma over his links with a wealthy family. Gwede Mantashe made the comments after deputy Finance Minister Mcebesi Jonas alleged the Gupta family had offered him a government promotion. During a rowdy parliamentary session, Mr Zuma denied the family had influenced cabinet appointments.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(10, 'Ex-leader Musharraf','Ex-leader Musharraf leaves Pakistan after travel ban lifted','Pakistan''s former military ruler Pervez Musharraf has left Pakistan to seek medical treatment in Dubai, days after the Supreme Court lifted a travel ban. His lawyers say he needs urgent spinal treatment unavailable in Pakistan. Mr Musharraf returned from self-imposed exile in 2013 to fight elections, but soon found himself fighting an array of charges relating to his time in power.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(11, 'Brazil judge','Brazil judge blocks Lula appointment to government','A Brazilian judge has blocked the appointment of ex-President Luiz Inacio Lula da Silva as chief of staff to his successor, Dilma Rousseff, shortly after he was sworn in. The judge''s injunction said there was a risk a federal investigation could be derailed if Lula was a minister. In Brazil, cabinet members can only be investigated by the Supreme Court, not by federal courts.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(12, 'Reason to sleap','Sleep does so many good things that we can''t tell which is the crucial one','There are a few things we literally cannot live without. Oxygen is one. Another is food and water. And then there is sleep: forcibly keep an animal awake for long enough and you will kill it. The same almost certainly applies to humans. This fact alone tells us that sleep must be doing something pretty important. But despite decades of intense scientific study there still is no consensus on exactly what that something is. Researchers have found that sleep is beneficial to humans in many ways: it helps us process memories, and keeps our social and emotional lives on track. Yet we still do not really know how, why or even exactly when sleep evolved.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(13, 'Smartwatches','Michael Kors, Tissot and Nixon join the smartwatch market','Michael Kors has become the latest fashion brand to offer smartwatches. The US firm has announced two timepieces - one targeted at each sex - powered by Google''s Android Wear. Samsung, Nixon and Fossil have also revealed new software-powered models at the Baselworld trade show. Swatch''s Tissot brand unveiled its first "connected watch" too, which links up to smartphones but does not run apps.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(14, 'EIU','Trump presidency rated among top 10 global risks: EIU','Donald Trump winning the US presidency is considered one of the top 10 risks facing the world, according to the Economist Intelligence Unit. The research firm warns he could disrupt the global economy and heighten political and security risks in the US. However, it does not expect Mr Trump to defeat Hillary Clinton who it sees as "his most likely Democratic contender".',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(15, 'Sex crime ','Universities ''should update sex crime guidelines''','Universities should overhaul guidelines on dealing with allegations of sexual assaults and harassment, according to a taskforce set up by the government. Current guidelines were written in 1994 and should be updated to reflect legal changes and the effect of social media, the Universities UK taskforce said. Key areas to be considered include better reporting systems and creating a "zero-tolerance culture", it said. The National Union of Students (NUS) and the government welcomed the review.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(16, 'Woman history','What writing about death taught one woman about life','When Heather Lende was asked to write an obituary for her local paper in Alaska, she had no idea that over the following 20 years she would go on write hundreds of them - all for people she knew. She also became an unofficial bereavement counsellor for the town of Haines. "A friend''s mother was old and dying at home. Nedra was her name, Nedra Waterman, and she was a pretty opinionated old gal," says Heather Lende.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(17, 'Lea Lea','Модная одежда отечественного производителя: миф или правда? Интервью с дизайнером марки Lea Lea','Слоган «Купляйце беларускае!» так долго предлагал нам старомодную одежду, что мы уже разучились верить в отечественные фабрики. А зря: среди них есть те, за кого как минимум не стыдно. Они в курсе последних тенденций, знают толк в качественной ткани и умеют подчеркнуть любую фигуру. Наш новый проект — как раз о таких. Это серия интервью с дизайнерами и руководителями белорусских фабрик, которые умеют шить красиво и стильно.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(18, 'Виктория Азаренко','Виктория Азаренко уверенно шагнула в полуфинал турнира в Индиан-Уэллсе','Виктория Азаренко (15-й номер мирового рейтинга) не испытала проблем в поединке против Магдалены Рыбариковой (97-й номер). Она выиграла все геймы, у соперницы было всего три брейк-поинта за матч, который длился один час и семь минут. Наиболее близка к очку на приеме Магдалена была в третьем гейме второго сета, когда у нее был тройной брейк-поинт. Впрочем, Виктория сумела вернуться в борьбу за этот балл и даже после двух двойных ошибок при ровном счете отвоевать его. Точку в матче Азаренко поставила подачей на вылет.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(19, 'Сирийские курды','Сирийские курды объявили о федерализации, вызвав возмущение Дамаска и Анкары','Свыше 30 политических партий, собравшихся на съезд в сирийском городе Румейлан (провинция Хасеке), официально объявили о создании региональной федеративной администрации на севере Сирии.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(20, 'Трансгенные растения','Ученые: "Трансгенные растения в Беларусь не завозят"','— Трансгенная картошка, которую мы выращиваем, используется исключительно в научных целях, - рассказала Валентина Лемеш, директор Института генетики и цитологии НАН Беларуси. — Конечно, было бы здорово получить генетически модифицированную линию, устойчивую к колорадскому жуку. Но, к сожалению, это очень дорогостоящий процесс. Навскидку, создание одного трансгенного сорта может стоить миллионы долларов.',CURRENT_TIMESTAMP,CURRENT_DATE);
insert into NEWS values(21, 'Подержанные автомобили','Из России с любовью. Сравниваем цены на подержанные автомобили в России и Беларуси','Последние два года Беларусь живет автомобилями из России. Поток подержанной техники оттуда пусть и перестал быть полноводным, но русло не пересохло. А мы посмотрим, что может противопоставить дешевым автомобилям из России простой белорусский продавец.',CURRENT_TIMESTAMP,CURRENT_DATE);

insert into NEWS_AUTHORS values(1,1);
insert into NEWS_AUTHORS values(2,2);
insert into NEWS_AUTHORS values(3,3);
insert into NEWS_AUTHORS values(4,4);
insert into NEWS_AUTHORS values(5,5);
insert into NEWS_AUTHORS values(6,6);
insert into NEWS_AUTHORS values(7,7);
insert into NEWS_AUTHORS values(8,8);
insert into NEWS_AUTHORS values(9,9);
insert into NEWS_AUTHORS values(10,1);
insert into NEWS_AUTHORS values(11,1);
insert into NEWS_AUTHORS values(12,2);
insert into NEWS_AUTHORS values(13,3);
insert into NEWS_AUTHORS values(14,4);
insert into NEWS_AUTHORS values(15,5);
insert into NEWS_AUTHORS values(16,6);
insert into NEWS_AUTHORS values(17,7);
insert into NEWS_AUTHORS values(18,8);
insert into NEWS_AUTHORS values(19,9);
insert into NEWS_AUTHORS values(20,2);
insert into NEWS_AUTHORS values(21,2);


insert into NEWS_TAGS values(1,1);
insert into NEWS_TAGS values(1,6);
insert into NEWS_TAGS values(2,8);
insert into NEWS_TAGS values(2,6);
insert into NEWS_TAGS values(3,6);
insert into NEWS_TAGS values(3,7);
insert into NEWS_TAGS values(3,4);
insert into NEWS_TAGS values(4,6);
insert into NEWS_TAGS values(4,7);
insert into NEWS_TAGS values(5,9);
insert into NEWS_TAGS values(6,6);
insert into NEWS_TAGS values(6,8);
insert into NEWS_TAGS values(7,1);
insert into NEWS_TAGS values(7,8);
insert into NEWS_TAGS values(8,1);
insert into NEWS_TAGS values(8,8);
insert into NEWS_TAGS values(8,6);
insert into NEWS_TAGS values(9,1);
insert into NEWS_TAGS values(9,8);
insert into NEWS_TAGS values(10,1);
insert into NEWS_TAGS values(11,1);
insert into NEWS_TAGS values(12,2);
insert into NEWS_TAGS values(12,5);
insert into NEWS_TAGS values(12,6);
insert into NEWS_TAGS values(13,6);
insert into NEWS_TAGS values(13,7);
insert into NEWS_TAGS values(13,9);
insert into NEWS_TAGS values(14,1);
insert into NEWS_TAGS values(14,9);
insert into NEWS_TAGS values(15,6);
insert into NEWS_TAGS values(16,6);
insert into NEWS_TAGS values(17,7);
insert into NEWS_TAGS values(18,2);
insert into NEWS_TAGS values(18,3);
insert into NEWS_TAGS values(18,6);
insert into NEWS_TAGS values(19,1);
insert into NEWS_TAGS values(21,9);